### ISSUE TITLE
To Do list (0.6.6)

### ISSUE THREAD

**Issue by Sniki** [Sniki/Lenovo-Thinkpad-T440S#3]
- [x] Update to Acidanthera kexts and OpenCore 0.6.6
- [ ] Add EDID patching section to fully enable Secure Boot on 1080p display panels
- [ ] Update AppleALC.kext with support for Docking Station Audio Jack
- [ ] Add Tools and procedures to generate SMBIOS values for new users
- [x] Add latest Sinetek-Rtsx.kext with full wake/sleep support and native SD Card Icon on mounted volumes.
- [x] Add latest VoodooRMI.kext & VoodooSMBus.kext

**Comment by i3p9** [comment]
Hey! Since you seem to be knowledgeable on the ALCFix-Swift, I wanted to ask you a question, the config.plist needed for ALCFix-Swift, how do you configure it? I'm on a T450s and I think we have the same codec (ALC292), can I use the one you made for your codec? 

Secondly, how did you figure out what to put in the config, I'm interested in knowing the process so that I can fix stuff if things break, and not use someone else's config blindly, thank you! 

Edit: Added audio codec dump for t450s here https://github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi/tree/master/Resources/AudioCodecDump

**Comment by Sniki** [comment]
> Hey! Since you seem to be knowledgeable on the ALCFix-Swift, I wanted to ask you a question, the config.plist needed for ALCFix-Swift, how do you configure it? I'm on a T450s and I think we have the same codec (ALC292), can I use the one you made for your codec?
> 
> Secondly, how did you figure out what to put in the config, I'm interested in knowing the process so that I can fix stuff if things break, and not use someone else's config blindly, thank you!
> 
> Edit: Added audio codec dump for t450s here https://github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi/tree/master/Resources/AudioCodecDump

Will add some more informations on upcoming release
